// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArQTZoveoHbYayoBm2SYV7m1rd5Aev3fY',
    appId: '1:549529099457:web:87cff0c5cd7b760565c840',
    messagingSenderId: '549529099457',
    projectId: 'udemyfluttersns',
    authDomain: 'udemyfluttersns.firebaseapp.com',
    storageBucket: 'udemyfluttersns.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqu-QdP2ecv5DCN_HbXff0Ymdm8IHlOg',
    appId: '1:549529099457:android:d5d5caace1c7cca865c840',
    messagingSenderId: '549529099457',
    projectId: 'udemyfluttersns',
    storageBucket: 'udemyfluttersns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwGnok0OMrHaTE0xuq2_1xb4CR4KfxQaU',
    appId: '1:549529099457:ios:5c10e0e44b2c56b165c840',
    messagingSenderId: '549529099457',
    projectId: 'udemyfluttersns',
    storageBucket: 'udemyfluttersns.appspot.com',
    iosClientId: '549529099457-ucdm4l6omlonfljkqogjld1fobtllthf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwGnok0OMrHaTE0xuq2_1xb4CR4KfxQaU',
    appId: '1:549529099457:ios:5c10e0e44b2c56b165c840',
    messagingSenderId: '549529099457',
    projectId: 'udemyfluttersns',
    storageBucket: 'udemyfluttersns.appspot.com',
    iosClientId: '549529099457-ucdm4l6omlonfljkqogjld1fobtllthf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );
}
